# Make python the default language because it is the weirdest to set up
language: python
python: "3.3"
env: CXX=/usr/bin/clang++ CC=/usr/bin/clang
before_install:
  - ./lang/cc/before_install
  - sudo apt-get update
install:
  - ./lang/cc/install
  - ./lang/go/install
  - ./lang/hs/install && export PATH=~/.cabal/bin:${PATH}
  - ./lang/java/install
  - ./lang/js/install
  - ./lang/py/install
before_script:
  - ./lang/cc/lint
  - ./lang/go/lint
  - ./lang/js/lint
  - ./lang/py/lint
script:
  - ./lang/cc/script
  - ./lang/go/script
  - ./lang/hs/script
  - ./lang/java/script
  - ./lang/js/script
  - ./lang/py/script
