language:
  - go
  - java
  - node_js
  - python
python:
  - "3.3"
install:
  - pip install nose
script:
#  - ./build/go/script
#  - ./build/java/script
#  - ./build/js/script
#  - ./build/py/script
  - nosetests
