# Make python the default language because it is the weirdest to set up
language: python
python: "3.3"
install:
  - ./lang/cc/install
  - ./lang/js/install
  - ./lang/py/install
before_script:
  - ./lang/go/lint
  - ./lang/js/lint
  - ./lang/py/lint
script:
  - ./lang/cc/script
  - ./lang/go/script
  - ./lang/java/script
  - ./lang/js/script
  - ./lang/py/script
