#!/usr/bin/env bash

set -e # Exit on error

for f in WORKSPACE $(find . -name "BUILD.bazel" -not -path "./node_modules/*")
do
  echo Checking $f
  yarn buildifier --lint=warn --mode=check --warnings=all $f
done
