# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test:
    # Use a machine executor because it most easily supports multiple languages
    machine:
      # See https://circleci.com/docs/2.0/configuration-reference/#machine for the list of images
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      # Install bazelisk. See https://github.com/bazelbuild/bazelisk#requirements
      - run: go get github.com/bazelbuild/bazelisk
      - run: bazelisk test --test_output=errors //...
  check-buildifier:
    docker:
      # See https://circleci.com/docs/2.0/docker-image-tags.json for a list of images
      - image: circleci/node:14.15.1@sha256:ef899d94629297c054d699e34b4293ba4fdd457117fe98afb016d499da3a9b43
    steps:
      - checkout
      - run: yarn install --frozen-lockfile --non-interactive
      - run: .circleci/check_buildifier
      - run:
          command: echo "Run .circleci/fix_buildifier"
          when: on_fail
  check-typescript:
    docker:
      # See https://circleci.com/docs/2.0/docker-image-tags.json for a list of images
      - image: circleci/node:14.15.1@sha256:ef899d94629297c054d699e34b4293ba4fdd457117fe98afb016d499da3a9b43
    steps:
      - checkout
      - run: yarn install --frozen-lockfile --non-interactive
      - run: .circleci/check_typescript
      - run:
          command: echo "Run .circleci/fix_typescript"
          when: on_fail
  check-json:
    docker:
      # See https://circleci.com/docs/2.0/docker-image-tags.json for a list of images
      - image: circleci/python:3.9.0@sha256:d021d72f8230f72990a5a382066ca5e6759d06fb5651326ef7172649afeddb97
    steps:
      - checkout
      - run: .circleci/check_json
      - run:
          command: echo "Run .circleci/fix_json"
          when: on_fail
  check-cc:
    docker:
      # See https://circleci.com/docs/2.0/docker-image-tags.json for a list of images
      - image: circleci/node:14.15.1@sha256:ef899d94629297c054d699e34b4293ba4fdd457117fe98afb016d499da3a9b43
    steps:
      - checkout
      - run: yarn install --frozen-lockfile --non-interactive
      - run: |
          find . -name *.h -o -name *.cc | xargs yarn clang-format --Werror -n -style="{BasedOnStyle: Google, Language: Cpp}"
      - run:
          command: |
            echo "Run find . -name *.h -o -name *.cc | xargs yarn clang-format -i -style=\"{BasedOnStyle: Google, Language: Cpp}\""
          when: on_fail
  check-java:
    docker:
      # See https://circleci.com/docs/2.0/docker-image-tags.json for a list of images
      - image: circleci/openjdk:14.0.2-buster@sha256:6e1b3a9fb6602885204373149bf3052ed8d0ba6e49f3836034c898d04c95be4e
    steps:
      - checkout
      - run: wget https://github.com/google/google-java-format/releases/download/google-java-format-1.8/google-java-format-1.8-all-deps.jar
      - run: find . -name *.java | xargs java -jar google-java-format-1.8-all-deps.jar --dry-run --set-exit-if-changed
      - run:
          command: |
            echo "Run find . -name *.java | xargs java -jar google-java-format-1.8-all-deps.jar --replace
          when: on_fail
  check-shell:
    docker:
      # See https://circleci.com/docs/2.0/docker-image-tags.json for a list of images
      - image: cimg/base:2020.12@sha256:a9adc0fb9b3d2440961a8042c5b03a387b3a0d6e2ab9e73ce20bff1ae84d64be
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install shellcheck
      - run: shellcheck tools/start_solution
  check-python:
    docker:
      # See https://circleci.com/docs/2.0/docker-image-tags.json for a list of images
      - image: circleci/python:3.9.0@sha256:d021d72f8230f72990a5a382066ca5e6759d06fb5651326ef7172649afeddb97
    steps:
      - checkout
      - run: pip install pylint
      - run: find . -name *.py | xargs pylint --indent-string='  ' --disable=missing-docstring --disable=too-many-public-methods
  check-go:
    docker:
      # See https://circleci.com/docs/2.0/docker-image-tags.json for a list of images
      - image: circleci/golang:latest@sha256:6dcc56cd8724f3661b5dac579fb04fccf0d02fc8a9fe9c689dd148b044e05ef6
    steps:
      - checkout
      # C++ files confuse vet
      - run: find . -name *.cc | xargs rm
      - run: go vet ./...

workflows:
  test-workflow:
    jobs:
      - check-buildifier
      - check-cc
      - check-go
      - check-java
      - check-json
      - check-python
      - check-shell
      - check-typescript
      - test
