# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test:
          #docker:
    # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
    #- image: circleci/golang:1.14.7
      #- image: circleci/python:3.8.5
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      # Install bazelisk. See https://github.com/bazelbuild/bazelisk#requirements
      - run: go get github.com/bazelbuild/bazelisk
      # Install python3 for haskell
      ##- run: sudo apt-get install python3
      - run: bazelisk test //...

workflows:
  test-workflow:
    jobs:
      - test
