# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test:
    # Use a machine executor because it most easily supports multiple languages
    machine:
      # See https://circleci.com/docs/2.0/configuration-reference/#machine for the list of images
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      # Install bazelisk. See https://github.com/bazelbuild/bazelisk#requirements
      - run: go get github.com/bazelbuild/bazelisk
      - run: bazelisk test //...
  check-buildifier:
    docker:
      - image: circleci/node:14.8.0
    steps:
      - checkout
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn buildifier --lint=warn -r .

workflows:
  test-workflow:
    jobs:
      - test
