# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test:
    # Use a machine executor because it most easily supports multiple languages
    machine:
      # See https://circleci.com/docs/2.0/configuration-reference/#machine for the list of images
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      # Install bazelisk. See https://github.com/bazelbuild/bazelisk#requirements
      - run: go get github.com/bazelbuild/bazelisk
      - run: bazelisk test //...
  check-buildifier:
    docker:
      # See https://circleci.com/docs/2.0/docker-image-tags.json for a list of images
      - image: circleci/node:14.9.0@sha256:5f1af93115f974e2a3e37684828deb1ad942f90bd1b47b0fc17b9e7580b5ce0b
    steps:
      - checkout
      - run: yarn install --frozen-lockfile --non-interactive
      - run: .circleci/check_buildifier
      - run:
          command: echo "Run .circleci/fix_buildifier"
          when: on_fail
  check-typescript:
    docker:
      # See https://circleci.com/docs/2.0/docker-image-tags.json for a list of images
      - image: circleci/node:14.9.0@sha256:5f1af93115f974e2a3e37684828deb1ad942f90bd1b47b0fc17b9e7580b5ce0b
    steps:
      - checkout
      - run: yarn install --frozen-lockfile --non-interactive
      - run: .circleci/check_typescript
      - run:
          command: echo "Run .circleci/fix_typescript"
          when: on_fail
  check-json:
    docker:
      # See https://circleci.com/docs/2.0/docker-image-tags.json for a list of images
      - image: circleci/python:3.8.5@sha256:e186ec95807f6108f500016c737aebf262fe5dd656e782d03ede317c0f623623
    steps:
      - checkout
      - run: .circleci/check_json
      - run:
          command: echo "Run .circleci/fix_json"
          when: on_fail
  check-cc:
    docker:
      # See https://circleci.com/docs/2.0/docker-image-tags.json for a list of images
      - image: circleci/node:14.9.0@sha256:5f1af93115f974e2a3e37684828deb1ad942f90bd1b47b0fc17b9e7580b5ce0b
    steps:
      - checkout
      - run: yarn install --frozen-lockfile --non-interactive
      - run: |
          find . -name *.h -o -name *.cc | xargs yarn clang-format --Werror -n -style="{BasedOnStyle: Google, Language: Cpp}"
      - run:
          command: |
            echo "Run find . -name *.h -o -name *.cc | xargs yarn clang-format -i -style=\"{BasedOnStyle: Google, Language: Cpp}\""
          when: on_fail
  check-java:
    docker:
      # See https://circleci.com/docs/2.0/docker-image-tags.json for a list of images
      - image: circleci/openjdk:14.0.2-buster@sha256:b23a1030486e2dbf677c3797e24b27c6e41f47ddaded5f8abbc57f4b3a277704
    steps:
      - checkout
      - run: wget https://github.com/google/google-java-format/releases/download/google-java-format-1.8/google-java-format-1.8-all-deps.jar
      - run: find . -name *.java | xargs java -jar google-java-format-1.8-all-deps.jar --dry-run --set-exit-if-changed
      - run:
          command: |
            echo "Run find . -name *.java | xargs java -jar google-java-format-1.8-all-deps.jar --replace
          when: on_fail
  check-shell:
    docker:
      # See https://circleci.com/docs/2.0/docker-image-tags.json for a list of images
      - image: cimg/base:2020.08@sha256:f19c30e3f8019f5c91fe14fc87c9f280293c5baef56f154e82d48fa5b1a21e86
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install shellcheck
      - run: shellcheck tools/start_solution

workflows:
  test-workflow:
    jobs:
      - check-buildifier
      - check-cc
      - check-java
      - check-json
      - check-shell
      - check-typescript
      - test
