#!/usr/bin/env bash

set -e # Exit on error

find . -name "BUILD.bazel" -not -path "./node_modules/*" \
  | xargs buildifier --lint=fix --mode=fix --warnings=all
buildifier --lint=fix --mode=fix --warnings=all MODULE.bazel
