#!/usr/bin/env bash

set -e # Exit on error

find . -name "BUILD.bazel" -not -path "./node_modules/*" \
  | xargs yarn buildifier --lint=fix --mode=fix --warnings=all
yarn buildifier --lint=fix --mode=fix --warnings=all WORKSPACE
